"""Restoration Impact Timeline (Feature 2 of FEATURE_CONTRACT_V2).

No new table -- derived entirely from the existing `site_analytics` rows.
`summary` below is template-filled from the computed `changes`; it is NOT
generated by an LLM.
"""

import uuid

from fastapi import HTTPException, status
from sqlalchemy.orm import Session

from app.models.analytics import SiteAnalytics
from app.repositories.analytics_repository import AnalyticsRepository
from app.repositories.risk_repository import RiskAssessmentRepository
from app.repositories.site_repository import SiteRepository
from app.schemas.impact_timeline import ImpactChanges, ImpactSnapshot, ImpactTimelineRead
from app.services.risk_service import compute_nature_health


def _direction(value: float, positive: str, negative: str) -> str:
    return positive if value >= 0 else negative


def _snapshot(record: SiteAnalytics) -> ImpactSnapshot:
    return ImpactSnapshot(
        recorded_at=record.recorded_at,
        carbon_captured_tco2e=record.carbon_captured_tco2e,
        biodiversity_score=record.biodiversity_score,
        vegetation_cover_percent=record.vegetation_cover_percent,
        species_count=record.species_count,
    )


class ImpactTimelineService:
    def __init__(self, db: Session):
        self.db = db
        self.sites = SiteRepository(db)
        self.analytics = AnalyticsRepository(db)
        self.assessments = RiskAssessmentRepository(db)

    def get_timeline(self, site_id: uuid.UUID, owner_id: uuid.UUID) -> ImpactTimelineRead:
        site = self.sites.get_by_id_for_owner(site_id, owner_id)
        if site is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Site not found")

        records = self.analytics.list_for_site(site.id)
        if not records:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="No analytics recorded yet for this site",
            )

        first = records[0]
        latest = records[-1]

        carbon_pct = (
            (latest.carbon_captured_tco2e - first.carbon_captured_tco2e)
            / max(first.carbon_captured_tco2e, 1)
            * 100
        )
        vegetation_pct = (
            (latest.vegetation_cover_percent - first.vegetation_cover_percent)
            / max(first.vegetation_cover_percent, 1)
            * 100
        )
        biodiversity_points = latest.biodiversity_score - first.biodiversity_score
        species_count_delta = latest.species_count - first.species_count

        latest_assessment = self.assessments.get_latest_for_site(site.id)
        nature_health_score_delta: float | None = None
        if latest_assessment is not None:
            as_of_first = compute_nature_health([first])
            nature_health_score_delta = latest_assessment.nature_health_score - as_of_first.score

        n_months = max(
            0,
            (latest.recorded_at.year - first.recorded_at.year) * 12
            + (latest.recorded_at.month - first.recorded_at.month),
        )

        summary = (
            f"Over the last {n_months} months, estimated carbon capture "
            f"{_direction(carbon_pct, 'increased', 'decreased')} by {abs(carbon_pct):.1f}%, "
            f"vegetation cover {_direction(vegetation_pct, 'improved', 'declined')} by "
            f"{abs(vegetation_pct):.1f}%, and biodiversity score "
            f"{_direction(biodiversity_points, 'improved', 'declined')} by "
            f"{abs(biodiversity_points):.1f} points."
        )

        return ImpactTimelineRead(
            first=_snapshot(first),
            latest=_snapshot(latest),
            changes=ImpactChanges(
                carbon_pct=round(carbon_pct, 2),
                biodiversity_points=round(biodiversity_points, 2),
                vegetation_pct=round(vegetation_pct, 2),
                species_count_delta=species_count_delta,
                nature_health_score_delta=(
                    round(nature_health_score_delta, 2)
                    if nature_health_score_delta is not None
                    else None
                ),
            ),
            summary=summary,
        )
