import uuid
from datetime import datetime

from pydantic import BaseModel

from app.models.enums import AlertStatus


class AlertRead(BaseModel):
    """A site alert. Alerts are demo intelligence data generated by fixed,
    documented threshold rules -- not a trained model output.
    """

    id: uuid.UUID
    site_id: uuid.UUID
    site_name: str
    project_id: uuid.UUID
    project_name: str
    assessment_id: uuid.UUID | None
    severity: str
    title: str
    description: str
    reasons: list[str]
    recommendation: str
    status: str
    reviewer_note: str | None
    created_at: datetime
    updated_at: datetime


class AlertListResponse(BaseModel):
    items: list[AlertRead]
    total: int


class AlertUpdate(BaseModel):
    """Partial update -- both fields optional. `reviewer_note` may be
    explicitly set to null to clear it.
    """

    status: AlertStatus | None = None
    reviewer_note: str | None = None


class AlertsSummary(BaseModel):
    open_count: int
    acknowledged_count: int
    resolved_count: int
    by_severity: dict[str, int]
    recent: list[AlertRead]
